# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='logo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='portrait',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='armor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operator',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='passcode',
            field=models.IntegerField(),
        ),
    ]
